name: .net build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TestServer-master/TestServer/TestServer.sln
    - name: Build TestServer
      run: dotnet build --no-restore TestServer-master/TestServer/TestServer.sln
    - name: Build TestServerTests
      run: dotnet build --no-restore TestServer-master/TestServerTests/TestServerTests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal TestServer-master/TestServerTests/TestServerTests.csproj
